"""initial_phase1_tables

Revision ID: e74ad56848cd
Revises:
Create Date: 2026-04-14 15:58:45.451563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74ad56848cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint(r"name ~ '^\d{4}-\d{4}$'", name='ck_seasons_name_format'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('home_team_name', sa.String(), nullable=False),
    sa.Column('home_team_code', sa.String(), nullable=False),
    sa.Column('away_team_code', sa.String(), nullable=True),
    sa.Column('away_team_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('competition', sa.String(), nullable=True),
    sa.Column('use_nbb_ref', sa.Boolean(), nullable=False),
    sa.Column('use_24s', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default='Scheduled'),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('matches_added', sa.Integer(), nullable=False),
    sa.Column('matches_updated', sa.Integer(), nullable=False),
    sa.Column('matches_removed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('zaaldienst_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'date', 'start_time')
    )
    op.create_table('match_timeslots',
    sa.Column('match_row_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_row_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_row_id', 'timeslot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_timeslots')
    op.drop_table('timeslots')
    op.drop_table('sync_log')
    op.drop_table('matches')
    op.drop_table('seasons')
    # ### end Alembic commands ###
